name: insert-ordered-containers
version: 0.1.0.0
synopsis: Associative containers retating insertion order for traversals.
description: Associative containers retating insertion order for traversals.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/insert-ordered-containers
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base                  
  - aeson                 
  - base-compat           
  - hashable              
  - lens                  
  - semigroupoids         
  - semigroups            
  - text                  
  - transformers          
  - unordered-containers

library:
  source-dirs: src

tests:
  ins-ord-containers-tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - base
      - insert-ordered-containers
      - tasty            
      - tasty-quickcheck 
      - QuickCheck        
